name: captain
version: 0.1.0
category: Web
author: Louis Pilfold
maintainer: louis@lpil.uk
copyright: 2017 Louis Pilfold
license: BSD3
github: lpil/captain
extra-source-files:
- README.md

dependencies:
  - Spock >=0.12
  - base >=4.7 && <5
  - wai >=3.0 && <4.0
  - wai-extra >=3.0 && <4.0

library:
  source-dirs: src

executables:
  captain-server:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - captain
      - Spock

tests:
  captain-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - hspec
      - captain
      - hspec-wai
